# Auto-labeling configuration
# Documentation: https://github.com/actions/labeler

# Features
feature:
  - changed-files:
    - any-glob-to-any-file: 'src/components/**'
  - changed-files:
    - any-glob-to-any-file: 'src/hooks/**'
  - changed-files:
    - any-glob-to-any-file: 'src/utils/**'
  - head-branch: ['feat/*', 'feature/*']
  - title: ['feat:', 'feature:']

# Bug fixes
bug:
  - head-branch: ['fix/*', 'bug/*', 'bugfix/*']
  - title: ['fix:', 'bug:', 'bugfix:']

# Documentation
documentation:
  - changed-files:
    - any-glob-to-any-file: 'README.md'
  - changed-files:
    - any-glob-to-any-file: 'docs/**'
  - changed-files:
    - any-glob-to-any-file: '*.md'
  - head-branch: ['docs/*', 'doc/*']
  - title: ['docs:', 'doc:']

# Dependencies
dependencies:
  - changed-files:
    - any-glob-to-any-file: 'package.json'
  - changed-files:
    - any-glob-to-any-file: 'package-lock.json'
  - changed-files:
    - any-glob-to-any-file: 'npm-shrinkwrap.json'
  - head-branch: ['deps/*', 'dependencies/*']
  - title: ['deps:', 'dependencies:']

# Chore/Maintenance
chore:
  - changed-files:
    - any-glob-to-any-file: '.github/**'
  - changed-files:
    - any-glob-to-any-file: 'tsconfig.json'
  - changed-files:
    - any-glob-to-any-file: 'vite.config.ts'
  - changed-files:
    - any-glob-to-any-file: 'biome.json'
  - head-branch: ['chore/*', 'maintenance/*']
  - title: ['chore:', 'maintenance:']

# Refactoring
refactor:
  - head-branch: ['refactor/*', 'refact/*']
  - title: ['refactor:', 'refact:']

# Performance
performance:
  - head-branch: ['perf/*', 'performance/*']
  - title: ['perf:', 'performance:']

# Security
security:
  - head-branch: ['security/*', 'sec/*']
  - title: ['security:', 'sec:']

# Testing
test:
  - changed-files:
    - any-glob-to-any-file: '**/*.test.{ts,tsx}'
  - changed-files:
    - any-glob-to-any-file: '**/*.spec.{ts,tsx}'
  - changed-files:
    - any-glob-to-any-file: 'src/test/**'
  - head-branch: ['test/*', 'tests/*']
  - title: ['test:', 'tests:']

# Styling
style:
  - changed-files:
    - any-glob-to-any-file: '**/*.css'
  - changed-files:
    - any-glob-to-any-file: '**/*.scss'
  - head-branch: ['style/*', 'styles/*']
  - title: ['style:', 'styles:']

# Configuration
config:
  - changed-files:
    - any-glob-to-any-file: '.github/**'
  - changed-files:
    - any-glob-to-any-file: '*.config.{js,ts}'
  - changed-files:
    - any-glob-to-any-file: '*.json'
  - head-branch: ['config/*', 'configuration/*']
  - title: ['config:', 'configuration:']
