name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'bugfix'
  - title: '🧹 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
  - title: '🔧 Refactoring'
    labels:
      - 'refactor'
  - title: '⚡ Performance'
    labels:
      - 'performance'
  - title: '🔒 Security'
    labels:
      - 'security'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'bugfix'
      - 'chore'
      - 'dependencies'
      - 'documentation'
  default: patch
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  ## 📦 Installation

  ```bash
  npm install
  ```

  ## 🚀 Quick Start

  ```bash
  npm run dev
  ```

  ## 🌐 Live Demo

  This version is automatically deployed to: https://hayato.github.io/todo-app-with-agent/

  ---

  *This release was automatically generated by [release-drafter](https://github.com/release-drafter/release-drafter)*
